### ISSUE TITLE
Idea: use smartphone camera geotagging to locate victims

### ISSUE THREAD

**Issue by tabinfl** [tdooner/irma-response-bot-api#16]
If they aren't sure where they are, have them snap a photo & parse out geotagging info if available. If not, volunteer may recognize the area.

**Comment by nealrs** [comment]
@tabinfl looks like the [cloudinary API has support for pulling exif data](http://cloudinary.com/documentation/admin_api#search_resources), so you could upload the file to cloudinary, query it for exit data, get the lat/lng, geocode it for zipcode, and then delete the source image. 

I'm more of a Python guy than node/js - but i'd be happy to work up a little code sample that can be adapted.

**Comment by nealrs** [comment]
@tabinfl @tdooner Following up on this, because I thought it'd be fun to look into. Per the [cloudinary docs](http://cloudinary.com/documentation/image_upload_api_reference#upload), you can upload/process: 

- a local file path (supported in SDKs only)
- the actual data (byte array buffer). 
- For example, in some SDKs, this could be an IO input stream of the data (e.g., File.open(file, "rb")).
- the Data URI (Base64 encoded), max ~60MB (62,910,000 chars)
- the remote FTP, HTTP or HTTPS URL address of an existing file
- an S3 URL of a whitelisted bucket

And when you upload a file, you can immediately return the metadata, so you can upload & delete immediately like in the following code snippet - which also does degree/minute/second conversion to decimal lat/long: 

```python
import cloudinary
import cloudinary.uploader
import cloudinary.api
import re

imgs = ["1.JPG", "2.JPG", "3.JPG"] # could be local files / images on s3 / the interwebs

def latlng(elat, elng):
    lat_deg = int(elat[:2])
    lat_min = float(re.search(r"\bdeg (..)", elat).group(1))
    lat_sec = float(re.search(r"\' (.*)\"", elat).group(1))
    lat_sgn = elat[-1:]
    lat = lat_deg + (lat_min/60) + (lat_sec/3600)

    lng_deg = int(elng[:2])
    lng_min = float(re.search(r"\bdeg (..)", elng).group(1))
    lng_sec = float(re.search(r"\' (.*)\"", elng).group(1))
    lng_sgn = elng[-1:]

    lng = lng_deg + (lng_min/60) + (lng_sec/3600)

    if lat_sgn == "S":
        lat = 0-lat
    if lng_sgn == "W":
        lng = 0-lng

    return [lat,lng]

def getCoords(imgs):
    for i in imgs:
        #upload image (with metadata return) & then delete it
        upload = cloudinary.uploader.upload(i, image_metadata=True)
        delete = cloudinary.uploader.destroy(upload['public_id'])
        print delete
        
        # if GPS data exists, grab that shit
        if 'GPSLatitude' in upload['image_metadata']:
            elat = upload['image_metadata']['GPSLatitude']
            elng = upload['image_metadata']['GPSLongitude']
            
            #convert to decimal lat/long (because EXIF data gives you ['40 deg 41\' 32.94" N', '73 deg 58\' 7.09" W']
            coords = latlng(elat,elng)
            print "We found some Lat/Lng data in that photo!"
            print coords
        else:
            print "No Lat/Lng Exif data found in photo"

        print "\n"

getCoords(imgs) # => [40.6924833333, -73.9686361111] <- and we can geocode that to lat/long use it directly in your api, right?
```

FYI, with the test images I used (attached) only one has Exif data. It took me a minute to realize I didn't have location services turned on for my Camera app. I imagine this is pretty common. 

![1](https://user-images.githubusercontent.com/1568188/30246018-16876162-95bb-11e7-8d8b-1816fbec0eea.JPG)
![2](https://user-images.githubusercontent.com/1568188/30246019-1687986c-95bb-11e7-8585-c48313a97f79.JPG)
![3](https://user-images.githubusercontent.com/1568188/30246020-16886562-95bb-11e7-87e9-77b9a3a4382f.JPG)

**Comment by tdooner** [comment]
This is a clever idea... but why not just ask people to hit the "Send Location" button that's in most texting apps now?

I'd bet that MMS messages are less reliable than raw photos from Camera apps at having embedded location information, since I believe they are typically downsized and highly compressed.
